# Aria2 configuration
dir=/var/lib/aria2/downloads
rpc-listen-port=6800
max-connection-per-server=16
rpc-secret=
enable-rpc=true
rpc-allow-origin-all=true
continue=true
save-session=/var/lib/aria2/aria2.session
input-file=/var/lib/aria2/aria2.session
